{
  "theme": "base",
  "themeVariables": {
    "darkMode": true,
    "background": "#19130f",
    "fontFamily": "Inter, system-ui, sans-serif",
    "fontSize": "15px",
    "primaryColor": "#2a1f17",
    "primaryTextColor": "#fbf3ea",
    "primaryBorderColor": "#fb923c",
    "secondaryColor": "#221a14",
    "tertiaryColor": "#221a14",
    "lineColor": "#b8a08c",
    "textColor": "#d8ccc0",
    "clusterBkg": "#1d1611",
    "clusterBorder": "#6b5444",
    "edgeLabelBackground": "#221a14",
    "actorBkg": "#2a1f17",
    "actorBorder": "#fb923c",
    "actorTextColor": "#fbf3ea",
    "actorLineColor": "#5a4636",
    "signalColor": "#d8ccc0",
    "signalTextColor": "#fbf3ea",
    "labelBoxBkgColor": "#221a14",
    "labelBoxBorderColor": "#fbbf24",
    "labelTextColor": "#fbbf24",
    "loopTextColor": "#d8ccc0",
    "noteBkgColor": "#3b2a10",
    "noteBorderColor": "#fbbf24",
    "noteTextColor": "#fde68a",
    "activationBkgColor": "#2a1f17",
    "activationBorderColor": "#fb923c"
  },
  "flowchart": { "curve": "basis", "padding": 16, "nodeSpacing": 45, "rankSpacing": 55 },
  "sequence": { "mirrorActors": false, "actorMargin": 70, "boxMargin": 12, "noteMargin": 12, "messageMargin": 42 }
}
